const types = {
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_FAILURE: 'ADD_USER_FAILURE',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_CURRENT_USER_FAILURE: 'SET_CURRENT_USER_FAILURE',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',
  CREATE_IDEA: 'CREATE_IDEA',
  CREATE_IDEA_FAILURE: 'CREATE_IDEA_FAILURE',
  FETCH_IDEAS: 'FETCH_IDEAS',
  UPDATE_IDEA: 'UPDATE_IDEA',
  REMOVE_IDEA: 'REMOVE_IDEA',
  ADD_COMMENT: 'ADD_COMMENT',
  FETECH_COMMENTS: 'FETCH_COMMENTS',
  SEARCH_IDEA: 'SEARCH_IDEA',
  ADD_ERROR: 'ADD_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
  GET_USER: 'GET_USER',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
};

export default types;
